version: "3"
services:
  modbus-server:
      container_name: modbus-server
      hostname: modbus
      image: ghcr.io/mrleongalaxyum/mymb:mb-docker-test
      restart: always
      command: -f /server_config.json
      ports:
        - 5020:5020

        

    
  influxdb:
    image: influxdb:2.4.0
    restart: always
    hostname: influxdb
    ports:
      - '8086:8086'

    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      
      
  influx-cli:
    #  initializes influxdb user/password/bucket...
    image: influxdb:2.4.0
    container_name: influx-cli
    depends_on:
      - influxdb
    command: sh -c 'sleep 5; influx setup --bucket "${INFLUX_DATA_BUCKET}" --token "${INFLUXDB_V2_TOKEN}" --org "${INFLUXDB_V2_ORG}" --username=${INFLUXDB_USERNAME} --password=${INFLUXDB_PASSWORD} --host=http://influxdb:8086 --force'
 
  grafana:
    image: ghcr.io/mrleongalaxyum/mygrafana:gf-docker-test
    restart: always
    hostname: grafana

    ports:
      - '3000:3000'

    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=100ms


    user: "1000"
    
  node-red:
    image: ghcr.io/mrleongalaxyum/kod-modbus-nr:nr-docker-test
    environment:
      - TZ=Europe/Zagreb
    restart: unless-stopped
    ports:
      - "1880:1880"
      
  python-modbus-sim:
    image: ghcr.io/mrleongalaxyum/mymbsim:py-docker-test
    restart: unless-stopped
   
    
volumes:
  influxdb-storage:

  grafana-storage:
