version: "3"
services:
  modbus-server:
      container_name: modbus-server
      hostname: modbus
      image: oitc/modbus-server
      restart: always
      command: -f /server_config.json
      ports:
        - 5020:5020
      volumes:
        - /home/leon/dockeri/kod-modbus/modbus-server/server_config.json:/server_config.json:ro
        
  telegraf:
    container_name: telegraf
    image: telegraf:latest
    restart: always
    links:
      - influxdb
    volumes:
      # Mount for telegraf config
      - /home/leon/dockeri/kod-modbus/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    #env_file:
    #  - /home/leon/dockeri/telegraf/influxv2.env:./influxv2.env
    #environment: 
    #  - DOCKER_INFLUXDB_INIT_ORG=kod
    #  - DOCKER_INFLUXDB_INIT_BUCKET=modbus-data
    #  - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=i7Mld6jpGDe7MhJEeZ1jjys-UVpLHRMRxOaBj_ao6G2-V-pY_4Gp0JuYmD5OJizgE8WzX2boCbBCLBFxaXtjtQ==
    
  influxdb:
    image: influxdb:latest
    restart: always
    hostname: influxdb
    ports:
      - '8086:8086'
    volumes:
      - /home/leon/dockeri/influxdb/storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  #chronograf:
    #image: chronograf:latest
    #restart: always
    #hostname: chronograf
    #ports:
    #   - '127.0.0.1:8888:8888'
    #volumes:
    #  - /home/leon/dockeri/chronograf/storage:/var/lib/chronograf
    #depends_on:
    #  - influxdb
   #environment:
     # - INFLUXDB_URL=http://influxdb:8086
     # - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
     # - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    restart: always
    hostname: grafana
    ports:
      - '3000:3000'
    volumes:
      - /home/leon/dockeri/kod-modbus/grafana/storage:/var/lib/grafana
      - /home/leon/dockeri/kod-modbus/grafana/provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_PANELS_DISABLE_SANITIZE_HTML=true


    user: "1000"
volumes:
  influxdb-storage:
  #chronograf-storage:
  grafana-storage:
    
    
