version: "3"
services:
  modbus-server:
      container_name: modbus-server
      hostname: modbus
      image: oitc/modbus-server
      restart: always
      command: -f /server_config.json
      ports:
        - 5020:5020
      volumes:
        - /home/leon/dockeri/kod-modbus/modbus-server/server_config.json:/server_config.json:ro
        

    
  influxdb:
    image: influxdb:2.4.0
    restart: always
    hostname: influxdb
    ports:
      - '8086:8086'
    volumes:
      - /home/leon/dockeri/kod-modbus/influxdb/storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      
      
  influx-cli:
    #  initializes influxdb user/password/bucket...
    image: influxdb:2.4.0
    container_name: influx-cli
    depends_on:
      - influxdb
    command: sh -c 'sleep 5; influx setup --bucket "${INFLUX_DATA_BUCKET}" --token "${INFLUXDB_V2_TOKEN}" --org "${INFLUXDB_V2_ORG}" --username=${INFLUXDB_USERNAME} --password=${INFLUXDB_PASSWORD} --host=http://influxdb:8086 --force'
 
  grafana:
    image: grafana/grafana:latest
    restart: always
    hostname: grafana

    ports:
      - '3000:3000'
    volumes:
      - /home/leon/dockeri/kod-modbus/grafana/storage:/var/lib/grafana
      - /home/leon/dockeri/kod-modbus/grafana/provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=100ms


    user: "1000"
volumes:
  influxdb-storage:

  grafana-storage:
